parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
  project: './tsconfig.json'

extends:
  - 'react-app'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - 'babel'
  - 'prettier'
  - '@typescript-eslint'

settings:
  react:
    version: 'detect'

env:
  browser: true

rules:
  no-debugger: 2
  prettier/prettier: 2
  import/first: off
  'react/prop-types': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-angle-bracket-type-assertion': off
  '@typescript-eslint/interface-name-prefix': off
  '@typescript-eslint/explicit-function-return-type': off
  'react/display-name': off
  'react/no-unescaped-entities': off
  '@typescript-eslint/explicit-member-accessibility': off 
  "@typescript-eslint/explicit-module-boundary-types": 1
  "@typescript-eslint/no-var-requires": off
  '@typescript-eslint/consistent-type-assertions':
    - error
    - assertionStyle: 'as'
      objectLiteralTypeAssertions: 'allow'

overrides:
  - files: '**/*.test.ts'
    rules:
      no-class-assign: 0
      no-console: 0
      no-unused-vars: 0
      no-unused-expressions: 0
