const DIRECTION_ASC = 'ASC';
const DIRECTION_DSC = 'DSC';

const STATUS_ACTIVE = 'ACTIVE';
const STATUS_CANCELED = 'CANCELED';
const STATUS_STOPPED = 'STOPPED';
const STATUS_REFUNDED = 'REFUNDED';

const STATUS_CODE_NOT_FOUND = 404;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_INTERNAL_SERVER_ERROR = 500;

module.exports = {
  DIRECTION_ASC,
  DIRECTION_DSC,
  STATUS_ACTIVE,
  STATUS_CANCELED,
  STATUS_STOPPED,
  STATUS_REFUNDED,
  STATUS_CODE_NOT_FOUND,
  STATUS_CODE_BAD_REQUEST,
  STATUS_CODE_INTERNAL_SERVER_ERROR,
};
