import React from 'react';
import {
  createMuiTheme,
  ThemeProvider,
  makeStyles,
} from '@material-ui/core/styles';
import theme from './theme';

import RecurringPaymentsTable from './components/RecurringPaymentsTable';
import CommitmentDetails from './components/CommitmentDetails';

const MUITheme = createMuiTheme(theme);

// css styles for App are specified here. The className is generated by 'makeStyles' when
// the 'useAppStyles' hook is run
const useAppStyles = makeStyles(theme => {
  return {
    app: {
      textAlign: 'center',
    },
    appHeader: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      fontSize: 'calc(10px + 2vmin)',
      color: 'white',
    },
    appLogo: {
      height: '100px',
      pointerEvents: 'none',
    },
    errorText: {
      color: theme.palette.error.main,
    },
    response: {
      fontFamily: 'monospace',
      whiteSpace: 'pre',
      textAlign: 'left',
    },
  };
});

const App = (): JSX.Element => {
  const classes = useAppStyles();

  // This Hook is used to keep track of whether to render the table or CommitmentDetails
  // const [displayDetails, setDisplayDetails] = React.useState(false);
  // This Hook is used to keep track of which CommitmentDetails should be displayed
  const [displayId, setDisplayId] = React.useState('');
  return (
    <ThemeProvider theme={MUITheme}>
      <div className={classes.app}>
        <header className={classes.appHeader}>
          <img src="logo.png" className={classes.appLogo} alt="logo" />
        </header>
        <div>
          {displayId ? (
            <CommitmentDetails
              displayId={displayId}
              setDisplayId={setDisplayId}
            />
          ) : (
            <RecurringPaymentsTable
              displayId={displayId}
              setDisplayId={setDisplayId}
            />
          )}
        </div>
      </div>
    </ThemeProvider>
  );
};

export default App;
